language: c
dist: trusty
sudo: false
git:
  submodules: false
addons:
  apt:
    packages:
    - 9base
    - libwayland-dev
    - lua5.2
    - nasm
    - pax
install:
- git clone --depth=1 https://github.com/michaelforney/oasis-toolchain /tmp/toolchain
- PATH=$PATH:/usr/lib/plan9/bin:/tmp/toolchain/bin
script:
- git submodule update --init pkg/samurai/src
- make -C pkg/samurai/src
- echo 'return { fs={exclude={}}, tls="libressl", video_drivers={intel=true, nouveau=true} }' > config.lua
- lua setup.lua
- ./pkg/samurai/src/samu out/pkg/openbsd/pax out/pkg/mc/bin/6m out/pkg/mc/bin/muse out/pkg/file/file out/pkg/texi2mdoc/texi2mdoc
- mkdir /tmp/bin
- cp out/pkg/openbsd/pax out/pkg/mc/bin/6m out/pkg/mc/bin/muse out/pkg/file/file out/pkg/texi2mdoc/texi2mdoc /tmp/bin
- PATH=/tmp/bin:$PATH
- ./pkg/samurai/src/samu commit
